services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - './client/src:/app/src'
    mem_limit: 512m
    cpus: 2
    # Windows fix for polling
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - './server/src:/app/src'
    mem_limit: 512m
    cpus: 2
    # Windows fix for polling
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  database:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: