services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - './client/src:/app/src'
    # Windows fix for polling
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true