services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - './client/src:/app/src'
    mem_limit: 512m
    cpus: 2
    # Windows fix for polling
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - './server/src:/app/src'
    mem_limit: 512m
    cpus: 2
    # Windows fix for polling
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true